# Generated by Django 4.1 on 2022-08-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid1', models.IntegerField()),
                ('uid2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Swiped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者的id')),
                ('sid', models.IntegerField(verbose_name='被滑动者的id')),
                ('status', models.CharField(choices=[('superlike', '超级喜欢'), ('like', '喜欢'), ('dislike', '不喜欢')], max_length=9)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
